env: "development"
storage_path: "postgres://go_practice:go_practice@localhost:5433/go_practice?sslmode=disable"
secret_key: "NtwPsVzOA6"
http_server:
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 60s
ldap:
  base_dn: "DC=mts,DC=local"
  bind_dn: "ldap-reader"
  bind_password: "t4iXrL5D"
  ldap_host: "dc-argus.vm.backservice.tech"
  ldap_port: 389
  groupDN: "cn=Users,dc=mts,dc=local"