env: "development"
storage_path: "postgres://go_practice:go_practice@localhost:5433/go_practice?sslmode=disable"
secret_key: "NtwPsVzOA6"
http_server:
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 60s